import swaggerJSDoc from 'swagger-jsdoc';

const swaggerOptions: swaggerJSDoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'My Express API',
      version: '1.0.0',
      description: 'API documentation generated by Swagger',
    },
    servers: [
      {
        url: 'http://100.116.248.20/api',
        description: 'Development server',
      },
    ],
  },
  // Point to your route files that include Swagger annotations
  apis: ['./src/router/*.ts', './src/routes/*.ts', '/src/controller/*.ts'],
};

export const swaggerSpec = swaggerJSDoc(swaggerOptions);
